[tool.anchor]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
discifi_sentinel = "FeMeEBKUt7iWk116n5UPm8fZApV91ngqFfQjMV8Zwhaa"

[programs.devnet]
discifi_sentinel = "FeMeEBKUt7iWk116n5UPm8fZApV91ngqFfQjMV8Zwhaa"

[registries]
solana = "https://api.devnet.solana.com"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NO_DNA=1 pnpm ts-mocha -p contracts/sentinel/tests/tsconfig.json -t 1000000 contracts/sentinel/tests/**/*.ts"

[workspace]
members = [
  "contracts/sentinel",
]
